version: '3.3'
services:
  app:
    image: myapi
    build:
      args:
        - target=dev
    environment:
      PORT: 8080
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USER: ${USERNAME}
      DB_PASSWORD: ${USERPASS}
      DB_NAME: ${DATABASE}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_APPLICATION_CREDENTIALS: ${GOOGLE_APPLICATION_CREDENTIALS}
    volumes:
      - .:/app
    ports:
      - "8080:8080"
  mysql:
    image: mysql:5.7
    platform: linux/amd64 # this needs for m1 user!
    container_name: db-for-go
    command:
        - --character-set-server=utf8mb4
        - --collation-server=utf8mb4_unicode_ci
        - --sql-mode=ONLY_FULL_GROUP_BY,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION
    environment:
        MYSQL_ROOT_USER: ${ROOTUSER}
        MYSQL_ROOT_PASSWORD: ${ROOTPASS}
        MYSQL_DATABASE: ${DATABASE}
        MYSQL_USER: ${USERNAME}
        MYSQL_PASSWORD: ${USERPASS}
        TZ: 'Asia/Tokyo'
    ports:
        - "3306:3306"
    volumes:
        - db-volume:/var/lib/mysql

volumes:
  db-volume:
